xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        //private IConfiguration configuration;
        private int idUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {
            this.categoryService = _categoryService;
            this.variantService = _variantService;

            //this.configuration = _configuration;
            //this.categoryService = new CategoryService(this.configuration);
            //this.variantService = new VariantService(this.configuration);
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower())
                || a.NameCategory.ToLower().Contains(searchString.ToLower())
             ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            //int createBy = idUser;
            VMResponse respon = await variantService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }
    }
}

xpos314.web/Views/Variant/Create.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Create Variant";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Create Variant</div>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                    "---Pilih Category---",
                    new { @class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to list</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 5
            },
            IdCategory : "required"
        },
        messeges: {
            NameVariant: {
                required: "Please fill name category",
                minlength: "The name must consist of at least 5 characters"
            },
            IdCategory : "Please select category"
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            $.ajax({
                type: "post",
                url: "/Variant/Create",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        toastr.success
                            (
                                data.message,
                                "",
                                {
                                    timeOut: 500,
                                    fadeOut: 500,
                                    onHidden: function () {
                                        window.location.reload()
                                    }
                                }
                            )

                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })
        }
    })

</script>

xpos314.web/Views/Variant/Delete.cshtml
@using xpos314.viewmodels
@model VMTblVariant

@{
    ViewData["Title"] = "Delete Variant";
    //Layout = null;
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h3>Are you sure for delete @Model.NameVariant ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" asp-controller="Variant" class="btn btn-light">Back to list</a>
            </div>

        </form>

    </div>
</div>

xpos314.web/Views/Variant/Detail.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Detail Variant";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Detail Variant</div>
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to list</a>
                </div>
            </div>
    </div>
</div>

xpos314.web/Views/Variant/Edit.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Edit Variant";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Edit Variant</div>
        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                    "---Pilih Category---",
                    new { @class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to list</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 5
            },
            IdCategory: "required"
        },
        messeges: {
            NameVariant: {
                required: "Please fill name category",
                minlength: "The name must consist of at least 5 characters"
            },
            IdCategory: "Please select category"
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            $.ajax({
                type: "post",
                url: "/Variant/Edit",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        toastr.success
                            (
                                data.message,
                                "",
                                {
                                    timeOut: 500,
                                    fadeOut: 500,
                                    onHidden: function () {
                                        window.location.reload()
                                    }
                                }
                            )

                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })
        }
    })

</script>

xpos314.web/Views/Variant/Index.cshtml
@using System.Globalization;
@using xpos314.datamodels
@using xpos314.viewmodels;
@model PaginatedList<VMTblVariant>

@{
    ViewData["Title"] = "Variant";
}

<div class="card">
    <div class="card-body">

        <h1 class="card-title mb-4">@ViewData["Title"]</h1>
        <form asp-action="Index" method="get" id="form_search">
            <div class="row mb-3">
                <div class="col-12">
                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

                        <div class="input-group w-50">
                            <input type="text" class="form-control" id="searchString" name="searchString" value="@ViewBag.currentFilter"
                                   placeholder="Search..." />

                            <div class="input-group-prepend">
                                <div class="input-group-text" id="btn_search"><i class="fas fa-search"></i></div>
                            </div>
                            <div class="input-group-prepend">
                                <div class="input-group-text" style="cursor:pointer" id="btn_reset"><i class="fas fa-redo"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <table class="table table-hover text-center mb-3">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.nameSort" asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageNumber="@ViewBag.PageIndex" asp-route-showData="@ViewBag.currentShowData">
                           <i class="fas fa-sort"></i> 
                           Name Variant
                        </a>
                    </th>
                    <th>Name Category</th>
                    <th>Description</th>
                    <th>Is Delete</th>
                    <th>Create Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.Count > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.NameVariant</td>
                                <td>@item.NameCategory</td>
                                <td>@item.Description</td>
                                <td>
                                    @if (item.IsDelete == true)
                                    {
                                        <input type="checkbox" checked disabled />
                                    }
                                    else
                                    {
                                        <input type="checkbox" disabled />
                                    }
                                </td>
                                <td>@item.CreateDate.ToString("dddd, dd MMMM yyyy HH:mm:ss", new CultureInfo("id-ID"))</td>
                                <td>
                                    <a class="btn btn-primary btn_edit" style="color: white" dataid="@item.Id">Edit</a>
                                    <a class="btn btn-success btn_detail" style="color: white" dataid="@item.Id">Detail</a>
                                    <a class="btn btn-danger btn_delete" style="color: white" dataid="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Data not found</td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        <div class="row mb-3">
            <div class="col-sm-12">
                <div class="d-flex justify-content-between">
                    <div class="btn-group">
                        <div class="mr-2">
                            show
                        </div>
                        <form asp-action="Index" id="form_pagesize">
                            <select name="PageSize" id="PageSize" aria-controls="zero_config" class="form-control form-control-sm w-auto">
                                <option value="3">3</option>
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="50">50</option>
                            </select>
                        </form>
                        <div class="ml-2">entries from @Model.TotalData data</div>
                        <input type="hidden" name="sortOrder" id="sort_change" value="" />
                    </div>
                    @{
                        var prevDisable = !Model.HasPreviousPage ? "disabled" : "";
                        var nextDisable = !Model.HasNextPage ? "disabled" : "";
                    }
                    <div class="w-auto">
                        Page @Model.PageIndex of @Model.TotalPages
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex - 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @prevDisable">
                            Previous
                        </a>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex + 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @nextDisable">
                            Next
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    $(document).ready(function () {
        
        $("#btn_search").click(function () {
            $("#sort_change").val("@ViewBag.CurrentSort")
            $("#form_search").submit()
        })

        $("#btn_reset").click(function () {
            $("#searchString").val("")
            $("#form_search").submit()
        })

        $("#btn_create").click(function () {
            $("#modal-body").empty();
            $("#modal-body").load("/Variant/Create")
            $("#myModal").modal("show");
        })

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#modal-body").empty();
            $("#modal-body").load("/Variant/Detail?id=" + id)
            $("#myModal").modal("show");
        })

        $(".btn_edit").click(function () {
            //alert("masuk")
            var id = $(this).attr("dataid")
            console.log(id)
            $("#modal-body").empty();
            $("#modal-body").load("/Variant/Edit?id=" + id)
            $("#myModal").modal("show");
        })

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#modal-body").empty();
            $("#modal-body").load("/Variant/Delete?id=" + id)
            $("#myModal").modal("show");
        })

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })
    })
</script>