xpos314.web/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.web.Models;

namespace xpos314.web.Controllers
{
    public class FriendController : Controller
    {
        private static List<Friend> list = new List<Friend>()
            {
                new Friend(){ Id = 1, Name = "Ahmad", Address = "Ampera Raya" },
                new Friend(){ Id = 2, Name = "Khoirul", Address = "Gg.Rini" },
                new Friend(){ Id = 3, Name = "Anwar", Address = "Ragunan" },
            };

        public IActionResult Index()
        {
            Friend friend = new Friend();
            
            //friend.Id = 3;
            //friend.Name = "Isni";
            //friend.Address = "Cimahi";

            //list.Add(friend);

            ViewBag.listFriend = list;

            return View(list);
        }

        public IActionResult Detail(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            list.Add(friend);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            return View(friend);
        }

        [HttpPost]
        public IActionResult Edit(Friend data)
        {
            Friend friend = list.Find(a => a.Id == data.Id)!;
            int index = list.IndexOf(friend);
            
            if (index > -1)
            {
                list[index].Id = data.Id;
                list[index].Name = data.Name;
                list[index].Address = data.Address;
            }

            return RedirectToAction("Index");
        }

        //public IActionResult Delete(int id)
        //{
        //    Friend friend = list.Find(a => a.Id == id)!;
        //    return View(friend);
        //}

        //[HttpPost]
        //public IActionResult Delete(string id)
        //{
        //    Friend data = list.Find(a => a.Id == int.Parse(id))!;
        //    list.Remove(data);
        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Friend friend = list.Find(a => a.Id == id)!;
            if (HttpContext.Request.Method == "POST")
            {
                list.Remove(friend);
                return RedirectToAction("Index");
            }
            else
            {
                return View(friend);
            }
        }
    }
}

xpos314.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int idUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService)
        {
            this.productService = _productService;
            this.orderService = _orderService;
        }

        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();
            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (dataSearch.NameProduct != null)
            {
                dataProduct = dataProduct.Where(a => a.NameProduct == dataSearch.NameProduct).ToList();
            }

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount &&
                                                a.Price <= dataSearch.MaxAmount).ToList();
            }

            //Set session in VMOrderHeader first load
            VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("listCart");

            if (dataHeader == null)
            {
                dataHeader = new VMOrderHeader();
                dataHeader.ListDetails = new List<VMOrderDetail>();
            }

            var listDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = listDetail;
            //End set session

            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.pageSize;

            return View(PaginatedList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.pageNumber ?? 1, dataSearch.pageSize ?? 3));
        }

        //Set session in VMOrderHeader evry add or minus
        [HttpPost]
        public JsonResult SetSession(VMOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexData("ListCart", dataHeader);
            return Json("");
        }
        //End

        //Remove Session
        public JsonResult RemoveSession()
        {
            HttpContext.Session.Remove("ListCart");

            return Json("");
        }
        //End

        public IActionResult OrderPreview(VMOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }

        public IActionResult SearchMenu()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> SubmitOrder(VMOrderHeader dataHeader)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            //dataHeader.IdCustomer = IdCustomer;
            
            dataHeader.IdCustomer = idUser;

            VMResponse respon = await orderService.SubmitOrder(dataHeader);
            return Json(respon);
        }

        public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            int IdCustomer = idUser;
            List<VMOrderHeader> data = await orderService.ListHeaderDetail(IdCustomer);
            int count = await orderService.CountTransaction(IdCustomer);
            ViewBag.Count = count;

            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;
            
            if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower().Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }

            if (dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where(a => a.CreateDate >= dataSearch.MinDate && 
                                  a.CreateDate <= dataSearch.MaxDate).ToList();
            }

            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount &&
                                  a.Amount <= dataSearch.MaxAmount).ToList();
            }

            ViewBag.Search = dataSearch;

            return View(data);
        }

        public IActionResult Search()
        {
            return PartialView();
        }
    }
}

xpos314.web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class ProductController : Controller
    {
        private ProductService productService;
        private VariantService variantService;
        private CategoryService categoryService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int idUser = 1;

        public ProductController(ProductService _productService, VariantService _variantService, CategoryService _categoryService, IWebHostEnvironment _webHostEnvironment)
        {
            this.productService = _productService;
            this.variantService = _variantService;
            this.categoryService = _categoryService;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameProduct.ToLower().Contains(searchString.ToLower())
                || a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.NameCategory.ToLower().Contains(searchString.ToLower())
             ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                case "price":
                    data = data.OrderBy(a => a.Price).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.Price).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }

            return View(PaginatedList<VMTblProduct>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();

            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm]VMTblProduct dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam);
            }

            VMResponse respon = await productService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> GetDataByIdCategory(int id)
        {
            List<VMTblVariant> data = await variantService.GetDataByIdCategory(id);
            return Json(data);
        }

        public string Upload(VMTblProduct dataParam)
        {
            string uniqeFileName = "";

            if (dataParam.ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqeFileName = Guid.NewGuid().ToString() + "_" + dataParam.ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqeFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    dataParam.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqeFileName;
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);

            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm]VMTblProduct dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam);
            }

            VMResponse respon = await productService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            //int createBy = idUser;
            VMResponse respon = await productService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", id);
        }
    }
}

xpos314.web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class RoleController : Controller
    {

        private RoleService roleService;
        private int idUser = 1;

        public RoleController(RoleService _roleService)
        {
            this.roleService = _roleService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<JsonResult> CheckNameIsExist(string roleName)
        {
            bool isExist = await roleService.CheckCategoryByName(roleName);
            return Json(isExist);
        }

        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblRole dataParam)
        {
            dataParam.CreatedBy = idUser;
            VMResponse respon = await roleService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TblRole dataParam)
        {
            dataParam.UpdatedBy = idUser;
            VMResponse respon = await roleService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            //int createBy = idUser;
            VMResponse respon = await roleService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }
    }
}

xpos314.web/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos314.web</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xpos314.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xpos314.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">Category Try</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - xpos314.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos314.web/Views/Shared/_Sidebar.cshtml
@{
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Home" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Friend" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                            Friend
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="CategoryTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category Try</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="VariantTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Variant Try</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Category" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Category</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Variant" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Variant</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Product" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Product</span>
                    </a>
                </li>

                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Order" asp-action="Catalog"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                            Menu Catalog
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Order" asp-action="HistoryOrder"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">
                            History Order
                        </span>
                    </a>
                </li>

                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Configuration</span></li>
                
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Role" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Role</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Customer" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Customer</span>
                    </a>
                </li>

                <li class="list-divider"></li>
                
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="authentication-login1.html"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->