xpos314.web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CustomerController : Controller
    {
        private RoleService roleService;
        private CustomerService customerService;
        private int idUser = 1;

        public CustomerController(RoleService _roleService, CustomerService _customerService)
        {
            this.roleService = _roleService;
            this.customerService = _customerService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblCustomer> data = await customerService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCustomer.ToLower().Contains(searchString.ToLower())
                                 || a.RoleName.ToLower().Contains(searchString.ToLower())
                                 ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCustomer).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCustomer).ToList();
                    break;
            }

            return View(PaginatedList<VMTblCustomer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblCustomer data = new VMTblCustomer();

            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);

            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);
            return PartialView(data);
        }


        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await customerService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);

            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }
    }
}

xpos314.web/Views/Customer/Create.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblCustomer
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Create Customer";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Create Customer</div>
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdRole" class="col-sm-4 col-form-label">Role Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole, "Id", "RoleName"),
                    "---Pilih Role---",
                    new { @class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Password" name="Password" value="@Model.Password">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to list</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameCustomer: {
                required: true,
                minlength: 5
            },
            IdRole: "required",
            Email: "required",
            Password: {
                required: true,
                minlength: 8
            },
            Phone: {
                required: true,
                minlength: 11
            },
            Address: "required"
        },
        messages: {
            NameCustomer: {
                required: "Please fill name customer",
                minlength: "The name must consist of at least 5 characters"
            },
            IdRole: "Please select role",
            Email: "Please fill email",
            Password: {
                required: "Please fill password",
                minlength: "The name must consist of at least 8 characters"
            },
            Phone: {
                required: "Please fill phone",
                minlength: "The name must consist of at least 11 characters"
            },
            address: "Please fill address"
        },

        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            $.ajax({
                type: "post",
                url: "/Customer/Create",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        toastr.success
                            (
                                data.message,
                                "",
                                {
                                    timeOut: 500,
                                    fadeOut: 500,
                                    onHidden: function () {
                                        window.location.reload()
                                    }
                                }
                            )

                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })
        }
    })

</script>

xpos314.web/Views/Customer/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCustomer

@{
    ViewData["Title"] = "Delete Customer";
    //Layout = null;
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h3>Are you sure for delete @Model.NameCustomer ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" asp-controller="Customer" class="btn btn-light">Back to list</a>
            </div>

        </form>

    </div>
</div>

xpos314.web/Views/Customer/Detail.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblCustomer
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Edit Customer";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Edit Customer</div>
        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="RoleName" class="col-sm-4 col-form-label">Role Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="RoleName" name="RoleName" value="@Model.RoleName" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Password" name="Password" value="@Model.Password" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone" readonly>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to list</a>
                </div>
            </div>
        </form>
    </div>
</div>

xpos314.web/Views/Customer/Edit.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblCustomer
@{
    //Layout = null;
    //Layout = Model == null ? null : Layout;
    ViewData["Title"] = "Edit Customer";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">Edit Customer</div>
        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdRole" class="col-sm-4 col-form-label">Role Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole, "Id", "RoleName"),
                    "---Pilih Role---",
                    new { @class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Password" name="Password" value="@Model.Password">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Address" name="Address" value="@Model.Address">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to list</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameCustomer: {
                required: true,
                minlength: 5
            },
            IdRole: "required",
            Email: "required",
            Password: {
                required: true,
                minlength: 8
            },
            Phone: {
                required: true,
                minlength: 11
            }
        },
        messages: {
            NameCustomer: {
                required: "Please fill name customer",
                minlength: "The name must consist of at least 5 characters"
            },
            IdRole: "Please select role",
            Email: "Please fill email",
            Password: {
                required: "Please fill password",
                minlength: "The name must consist of at least 8 characters"
            },
            Phone: {
                required: "Please fill phone",
                minlength: "The name must consist of at least 11 characters"
            }
        },

        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            $.ajax({
                type: "post",
                url: "/Customer/Edit",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        toastr.success
                            (
                                data.message,
                                "",
                                {
                                    timeOut: 500,
                                    fadeOut: 500,
                                    onHidden: function () {
                                        window.location.reload()
                                    }
                                }
                            )

                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })
        }
    })

</script>

xpos314.web/Views/Customer/Index.cshtml
@using System.Globalization;
@using xpos314.datamodels
@using xpos314.viewmodels;
@model PaginatedList<VMTblCustomer>

@{
    ViewData["Title"] = "Customer";
}

<div class="card">
    <div class="card-body">

        <h1 class="card-title mb-4">@ViewData["Title"]</h1>
        <form asp-action="Index" method="get" id="form_search">
            <div class="row mb-3">
                <div class="col-12">
                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

                        <div class="input-group w-50">
                            <input type="text" class="form-control" id="searchString" name="searchString" value="@ViewBag.currentFilter"
                                   placeholder="Search..." />

                            <div class="input-group-prepend">
                                <div class="input-group-text" id="btn_search"><i class="fas fa-search"></i></div>
                            </div>
                            <div class="input-group-prepend">
                                <div class="input-group-text" style="cursor:pointer" id="btn_reset"><i class="fas fa-redo"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <table class="table table-hover text-center mb-3">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.nameSort" asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageNumber="@ViewBag.PageIndex" asp-route-showData="@ViewBag.currentShowData">
                           <i class="fas fa-sort"></i> 
                           Name Customer
                        </a>
                    </th>
                    <th>Role Name</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.Count > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.NameCustomer</td>
                                <td>@item.RoleName</td>
                                <td>@item.Email</td>
                                <td>@item.Password</td>
                                <td>@item.Address</td>
                                <td>@item.Phone</td>
                                <td>
                                    <a class="btn btn-primary btn_edit" style="color: white" dataid="@item.Id">Edit</a>
                                    <a class="btn btn-success btn_detail" style="color: white" dataid="@item.Id">Detail</a>
                                    <a class="btn btn-danger btn_delete" style="color: white" dataid="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="7">Data not found</td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        <div class="row mb-3">
            <div class="col-sm-12">
                <div class="d-flex justify-content-between">
                    <div class="btn-group">
                        <div class="mr-2">
                            show
                        </div>
                        <form asp-action="Index" id="form_pagesize">
                            <select name="PageSize" id="PageSize" aria-controls="zero_config" class="form-control form-control-sm w-auto">
                                <option value="3">3</option>
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="50">50</option>
                            </select>
                        </form>
                        <div class="ml-2">entries from @Model.TotalData data</div>
                        <input type="hidden" name="sortOrder" id="sort_change" value="" />
                    </div>
                    @{
                        var prevDisable = !Model.HasPreviousPage ? "disabled" : "";
                        var nextDisable = !Model.HasNextPage ? "disabled" : "";
                    }
                    <div class="w-auto">
                        Page @Model.PageIndex of @Model.TotalPages
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex - 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @prevDisable">
                            Previous
                        </a>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex + 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @nextDisable">
                            Next
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>

    $(document).ready(function () {
        
        $("#btn_search").click(function () {
            $("#sort_change").val("@ViewBag.CurrentSort")
            $("#form_search").submit()
        })

        $("#btn_reset").click(function () {
            $("#searchString").val("")
            $("#form_search").submit()
        })

        $("#btn_create").click(function () {
            $("#modal-body").empty();
            $("#modal-body").load("/Customer/Create")
            $("#myModal").modal("show");
        })

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#modal-body").empty();
            $("#modal-body").load("/Customer/Detail?id=" + id)
            $("#myModal").modal("show");
        })

        $(".btn_edit").click(function () {
            //alert("masuk")
            var id = $(this).attr("dataid")
            console.log(id)
            $("#modal-body").empty();
            $("#modal-body").load("/Customer/Edit?id=" + id)
            $("#myModal").modal("show");
        })

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#modal-body").empty();
            $("#modal-body").load("/Customer/Delete?id=" + id)
            $("#myModal").modal("show");
        })

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })
    })
</script>